services:
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    environment:
      - "CF_API_EMAIL=agustinng14@gmail.com"
      - "CF_API_KEY=03a8f2adabd7c6f22b7cb4f7d5bbdfc6fac1a"
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.mqtt.address=:1883"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le.acme.email=dev@kriollotech.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.backend.kriollotech.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$apr1$JmB4T2Zj$unPEAZSPYQmOUX.8XONLm1"

    ports:
      - "80:80"
      - "443:443"
      - "1883:1883"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true

volumes:
  cache:
    driver: local
  letsencrypt:
    driver: local
