services:
  sql-db:
    environment:
      - MYSQL_ROOT_PASSWORD
    build:
      context: ./mariadb
    image: maria-db
    container_name: maria-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    mem_limit: 3g
    labels:
      - "traefik.enable=false"
    memswap_limit: -1
    mem_swappiness: 20
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      traefik-net:
        aliases:
          - db

  tomcat:
    build:
      context: ./tomcat
    image: tomcat
    container_name: tomcat-vemetris
    restart: unless-stopped
    ports:
      - ":8080"
      - ":8000"
    mem_limit: 3g
    memswap_limit: -1
    mem_swappiness: 20
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vemetris.rule=Host(`monitoring.kriollotech.com`)"
      - "traefik.http.services.vemetris.loadbalancer.server.port=8080"
      - "traefik.http.routers.vemetris.entrypoints=websecure"
      - "traefik.http.routers.vemetris.tls.certresolver=le"
      - "traefik.http.routers.vemetris.middlewares=vemetris-timeout"
      - "traefik.http.middlewares.vemetris-timeout.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.vemetris-timeout.headers.sslredirect=true"
      - "traefik.http.middlewares.vemetris-timeout.headers.stsSeconds=315360000"
      - "traefik.http.middlewares.vemetris-timeout.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.vemetris-timeout.headers.stsPreload=true"
      - "traefik.http.middlewares.vemetris-timeout.headers.forceSTSHeader=true"
    healthcheck:
      test: ["CMD", "bash", "/healthCheck.sh"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      traefik-net:
        aliases:
          - tomcat
    depends_on:
      sql-db:
        condition: service_healthy

  mqtt-modbus:
    environment:
      - MQTT_PORT=1883
      - MQTT_HOST=127.0.0.1
      - MQTT_USER=Vemetris
      - MQTT_PASS=Vemetris
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      # This is the port for the mqtt broker
      - "1883:1883"
      # These are the ports for the http server
      - "3001:3001"
      # These are the ports for the modbus slaves include more as needed
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
      - "8034:8034"
      - "8035:8035"
      - "8036:8036"
      - "8037:8037"
      - "8038:8038"
      - "8039:8039"
      - "8040:8040"
    build:
      context: ./mqtt_modbus
    image: mqtt
    container_name: mqtt-modbus
    restart: unless-stopped
    mem_limit: 3g
    memswap_limit: -1
    mem_swappiness: 20
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mqtt.rule=Host(`mqtt.backend.kriollotech.com`)"
      - "traefik.port=1883"
      - "traefik.http.routers.mqtt.entrypoints=websecure"
      - "traefik.http.routers.mqtt.tls.certresolver=le"

    depends_on:
      tomcat:
        condition: service_healthy
    networks:
      traefik-net:
        aliases:
          - mqtt

  redis:
    image: redis:bookworm
    labels:
      - "traefik.enable=false"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - mqttData:/data
    # depends_on:
    #   - traefik
    networks:
      traefik-net:
        aliases:
          - redis

networks:
  traefik-net:
    external: true

volumes:
  mqttData:
